name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  Build:
    # Name the Job
    name: Execute unit tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6.0', '3.7.0', '3.8.0', '3.9.0']
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      # Sets up multiple versions of python, credit: https://github.com/actions/setup-python
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-verison: ${{ matrix.python-version }}
      # Installs requirements
      - name: Install Requirements
        run: |
          sudo apt-get install tesseract-ocr
          python -m pip install --upgrade pip
          pip install opencv-python
          pip install pytesseract
      # Display python version
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
      # Runs unit tests
      - name: Run Unit Tests
        run: |
          python -m unittest discover tests/
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}